chain_id: 2
indexer_endpoint: "35.223.137.149:50051"
indexer_api_key: "kLtfHYRtnB7KkRcA3HG4l19HOoyYlp79i24HswRXeh3eCA5DpB_HsrRaNRvsBqlo"
db_connection_uri: "sqlite:///tontine.testnet.db"
starting_version: 526606790
tontine_module_address: "0xb078d693856a65401d492f99ca0d6a29a0c5c0e371bc2521570a86e40d95f823"
tontine_module_name: "tontine07"
api_port: 6780
run_processor: true
